{% set name = "kfilemetadata" %}
{% set version = "5.76.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kfilemetadata-{{ version }}.tar.xz
  sha256: fa24758c93ce3df9f8ced4310dc0bf58e129b08e50f254daafa025afc9213d68

build:
  number: 5
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kfilemetadata', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - attr
    - exiv2
    - ffmpeg
    - poppler
    - ki18n >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - karchive >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}
  run:
    - exiv2

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5FileMetaData.so

about:
  home: https://api.kde.org/frameworks/kfilemetadata/html/index.html
  license: BSD-3-Clause AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Simple library for extracting metadat
  description: |
    KFileMetaData provides a simple library for extracting the
    text and metadata from a number of different files. This library
    is typically used by file indexers to retreive the metadata.
    This library can also be used by applications to write metadata.
  dev_url: https://cgit.kde.org/kfilemetadata.git/tree

extra:
  recipe-maintainers:
    - scopatz
