travis:
  secure:
    BINSTAR_TOKEN: 00iWkXb0+8Uj3ds66WpUSszxZKQGTbvo6jYEj1J4HW5jDGRXnCJibU0VYmteFf6BnV8RjqAtXkrRhw0c7tvFZqyy1m2daZq/swBpPAiTteWZPHTo44EIzBWRIBzPkpwvo8pZM2FilJ0Jlvn+EZKmBwr5H8mdF7RLt7uLBIQwY+Lo3omqtq+zKqHW8hUFNTlFaClrY3V3UMVBuoks0TomsmtaQ9GvAJ3Iva60bGkYF7KqwJPggrJnAg1I6vvyKQqw/8BVOiCbv72vJnrJweDTAReAswbfHfLHLvLPNgNL/Gq9R4hvbbKIOu8DpOa+l4VDkiNO8LwrsjH0HfUmpac+SHxz+DcthZyZ1DVRTXj30T8UNcebDWFTzXnTYs0cLjoAFSCsUTUTkZR/IN4zYPBF3k6wdiW7A0aoOjQ24dY2ZlOkNpXBDykSGxN8w7vpOKwup1qKmvtCQn6c38j/r1+wU0D+teV/w1lcCGLr516nrN30IIx50ChqW8134EWnIl71XfKUD4wKs0PwxSfxkSDouKv37/DqfLGUUUQ2jkNJ5OrlLU4YKvXOSjqxePJK9RGJRbf407oRP+II9BngHKvSqr4M+Blp6DAg6jlAU92a19AMqKPgoeCevsuS9L9LafOgqSxNT4zP0unF7oOw1JjtpeB1RaXzgNFSzYvxADQ7sg0=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
